app.name=TodoApp
app.version=2.0

# PostgreSQL Database Configuration
db.driver=com.mysql.cj.jdbc.Driver
#db.url=jdbc:postgresql://125.212.224.35:5432/Programmize
db.url=jdbc:mysql://programmize-doanminhcuong0702-0a97.g.aivencloud.com:11985/programmize
db.username=avnadmin
db.password=AVNS_YogZXZS2vXpfHaAinNC

# Connection Pool Settings (optional)
db.pool.minIdle=5
db.pool.maxIdle=10
db.pool.maxTotal=20

# Connection Timeout (milliseconds)
db.timeout.connection=30000
db.timeout.validation=5000


#Mailer Credentials
mailer.host=smtp.gmail.com
mailer.port=587
mailer.username=programmize178@gmail.com
mailer.password=czbz lsux olbo yirw
mailer.fromMail=giahuy178@gmail.com
mailer.fromName=Nguyen Gia Huy
mailer.reply2=HuyXyz@gmail.com