app.name=TodoApp
app.version=2.0

# PostgreSQL Database Configuration
db.driver=com.mysql.cj.jdbc.Driver
#db.url=jdbc:postgresql://125.212.224.35:5432/Programmize
db.url=
db.username=
db.password=

# Connection Pool Settings (optional)
db.pool.minIdle=5
db.pool.maxIdle=10
db.pool.maxTotal=20

# Connection Timeout (milliseconds)
db.timeout.connection=30000
db.timeout.validation=5000


#Mailer Credentials
mailer.host=
mailer.port=
mailer.username=
mailer.password=
mailer.fromMail=
mailer.fromName=
mailer.reply2=
